### ISSUE TITLE
how to install/run the game?

### ISSUE THREAD

**Issue by zilveer** [jgao18/PokerRoom#100]
Hello,
How can I install / run the game ?

Please give me some instructions .

Thanks for your help.

**Comment by zilveer** [comment]
Anyone ? Please help me.

**Comment by jcisneros21** [comment]
Hello zilveer,

Thank you for taking an interest with our game! All of the developers, including me, are busy currently with other issues this week. I apologize for the inconvenience we caused you for this late response.

You need to have nodejs installed on your machine. I currently have nodejs version 4.2.6 on my machine and it worked perfect just now. I think any version that is version 3 or more should work but I could be wrong. Once nodejs is installed, please use your terminal or cmd if you are using windows and enter our repository. Once entered run the command:

node gameserver.js 9000
note: (It could be any available port number beside 9000)

Once the game server has started, which you can see when it prints out "Game server started on port 9000", you can then open a browser such as Chrome or Internet Explorer and enter **your IP address** and **port number** like what is shown below.

[IP address]:[Port Number]

Mine was like this:

192.168.1.9:9000

The game should be running now! We do have a database with creation of different poker rooms for all kinds of users however I think this is sufficient for you to play this game and see how you like it. You do need two players to actually play the poker game so bring up two tabs with the game and you can see another user enter the room.

If you have any other questions please let us know. I apologize again for our lack of communication.

Thank you,
Jessie Cisneros

**Comment by zilveer** [comment]
Hello Jessie, 
And thank you very much for replying back,
 I really appreciate it!

Regarding the Database ,
Should I just iimport the database found in this repository?
And if so where do I change the database settings ?

Thank you once again for taking your time replying back to me.

I will test the game later today after my work. Looking forward to it. Is there any known bugs ?

**Comment by bpokhrel** [comment]
zilveer,
         You need to create your own database on your computer. You are welcome to use our sql code to create database and tables.
Thanks
Bikram Pokhrel

**Comment by zilveer** [comment]
Thanks.. The instructions were correct and I could run it exactly as described.

Thx for your help!
