### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jgao18** [jgao18/PokerRoom#70]
List of bugs found from beta-testing

**Comment by jgao18** [comment]
(mattchainsaw) if remember me is selected, the login.php redirects to a blank login.php page

**Comment by jgao18** [comment]
clicking "check/call" after clicking raise keeps the raise amount buttons active

**Comment by jgao18** [comment]
folding doesn't display properly for clients

**Comment by mattchainsaw** [comment]
elephant.io-master/src/Engine/SocketIO/Version1X.php: line 48

Uncaught exception 'ElephantIO\Exception\ServerConnectionFailureException'
